### ISSUE TITLE
No such file or directory, scandir 'usr/share/vala-0.32/vapi/' at Error (native)

### ISSUE THREAD

**Issue by rastersoft** [Bat41/valhalla#22]
Hi:
I receive this error in the log every time I launch Atom.

```
Error: ENOENT: no such file or directory, scandir 'usr/share/vala-0.32/vapi/' at Error (native)
/home/raster/.atom/packages/valhalla/lib/provider.js:90
```

At /usr/share I have vala, vala-0.26, vala-0.30 and vala-0.34

**Comment by Bat41** [comment]
Thanks for the bug report. I'll fix it in the next release, but if you want to fix it now, you can go to your settings, then the `Packages` section, find Valhalla, and edit the VAPIs directories with `vala-0.34` instead of `vala-0.32`. :)

**Comment by rastersoft** [comment]
Oh, ok... I was searching for that in the source code itself but was unable to find it.

**Comment by rastersoft** [comment]
BTW: it seems that, by default, it doesn't include the '/' at the beginning of "usr/share...".

**Comment by rastersoft** [comment]
Maybe it would be better to use always the biggest version, unless specified in the settings...

**Comment by Bat41** [comment]
Yes, presently the version is hardcoded. :grin: But I'll just spawn `valac --version` to get the version.
