### ISSUE TITLE
Closing a scope that is not open

### ISSUE THREAD

**Issue by rastersoft** [Bat41/valhalla#23]
Hi again:

I also receive this error everytime I open Atom:

```
scopes.js [sm]:354
Closing a scope that is not open.(/home/raster/workspace/autovala/src/autovalaLib/elementValaBinary.vala)

parse @ scopes.js [sm]:354
(anonymous function) @ provider.js [sm]:46
module.exports.Emitter.simpleDispatch @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25
module.exports.Emitter.emit @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129
(anonymous function) @ /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427

provider.js [sm]:369 Resolving ! undefined
```

It happens with elementValaBinary.vala, packages_pacman.vala and vileview.vala; all from Autovala.

**Comment by Bat41** [comment]
Yes, I use a custom parser for Vala code, but it could contains bugs. This message is in the developers console, right ?

**Comment by rastersoft** [comment]
Yes, in the developer consoles. I also receive it in xcb.vapi. If you want, I can attach all the files with errors.

**Comment by Bat41** [comment]
OK, so it's not really disturbing at least. I also have the error with xcb.vapi, so I don't need your files thanks. :)

**Comment by Bat41** [comment]
The part of the code which was throwing this error doesn't exist anymore.
