### ISSUE TITLE
Wrong vapi location

### ISSUE THREAD

**Issue by naaando** [Bat41/valhalla#29]
There are some files on /usr/share/vala/vapi, and some others on /usr/share/vala-(Version)/vapi
On doc, when I open granite for example, ..vala/vapi/ its being open as /usr/share/vala:/usr/share/vala-(Version)/vapi/granite.vapi , a empty file, and ../vala-(Version)/vapi isn't being listed at all.

Get me in touch if I can address some more details...

**Comment by Bat41** [comment]
Hum... That's strange. `../vala/vapi` is a folder in one of the project you have opened in Atom, right?

I'm currently rewriting a big part of the package from scratch, I hope your problem will be fixed with this new version. :)

**Comment by naaando** [comment]
Nope, I mean it's the /usr/share/vala/vapi, Valhala, couldn't open the vapi, and Atom can't open in file manager because it can't understand the location '/usr/share/vala/vapi/:/usr/share/vala-0.32/vapi/granite.vapi for example.
Which is at /usr/share/vala/vapi/granite.vapi

Nice job so far. ;)

Screenshot
![image](https://cloud.githubusercontent.com/assets/12532760/22706107/2e9fbd8a-ed55-11e6-8f06-5a64c095a57c.png)

**Comment by Bat41** [comment]
Ah OK, I understand the problem. It will  be fixed in next version I think. :)

**Comment by Bat41** [comment]
Do you stil have this problem with v1.0.0?

**Comment by naaando** [comment]
I couldn't test due to another two errors, 
"Uncaught TypeError: Cannot read property 'explore' of undefined"
"Uncaught TypeError: Cannot read property 'path' of undefined"

**Comment by Bat41** [comment]
Hum... the same problem as #32

**Comment by Bat41** [comment]
I fixed #32, could you update to 1.0.5 and tell if it works please? 🙂

**Comment by naaando** [comment]
Yeah, the path seems to be recognized now, many thanks !
